reviews:
  poem: false
  sequence_diagrams: false
  suggested_reviewers: false
  collapse_walkthrough: true
  related_prs: false

# Trigger reviews on dev branch, disable on main
base_branches:
  - dev

